services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    command: python bot/main.py
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    env_file:
      - ./.env
volumes:
  postgres_data: