services:
  bot:
    build:
      dockerfile: Dockerfile
    command: python main.py
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env
volumes:
  postgres_data: